# Note: This file handles Continuous Integration (CI), and is separate from the main_helpcare.yml CD file.

# Handles continuous integration (CI) tasks like running tests across multiple Python versions
# Can run tests without triggering deployment to Azure
name: Django CI

# Runs on all push and pull requests to main branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Check for outdated packages
      run: |
        pip list --outdated
    - name: Check for security vulnerabilities
      run: |
        pip install safety
        safety check
    - name: Run Tests
      run: |
        python manage.py test
