# Note: This file handles Continuous Integration (CI), and is separate from the main_helpcare.yml CD file.

# Handles continuous integration (CI) tasks like running tests across multiple Python versions
# Can run tests without triggering deployment to Azure
name: Django CI

# Runs on all push and pull requests to main branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Check for security vulnerabilities
      run: |
        pip install safety
        safety check
    - name: Run Tests
      run: |
        pytest
