# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

# Note: This file handles Continuous Deployment (CD), and is separate from the django.yml CI file.


# Azure deployment runs on push to main and manual triggers (workflow_dispatch)
# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

# Note: This file handles Continuous Deployment (CD).


# Azure deployment runs on push to main and manual triggers (workflow_dispatch)
name: Azure Web App Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: https://helpcare-egcpaqffcefdaag0.canadacentral-01.azurewebsites.net

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


      # Create lightweight deployment package
      - name: Create deployment package
        run: |
          # Remove any existing static files to reduce package size
          rm -rf static/
          # Create minimal zip package
          zip -r deploy.zip . -x "*.git*" "*.github*" "*.pytest_cache*" "*.vscode*" "*.pyc" "__pycache__/*" "*.sqlite3"

      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'HelpCare'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: deploy.zip
          clean: true
