# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

# Note: This file handles Continuous Deployment (CD), and is separate from the django.yml CI file.


# Azure deployment runs on push to main and manual triggers (workflow_dispatch)
# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

# Note: This file handles Continuous Deployment (CD), and is separate from the django.yml CI file.


# Azure deployment runs on push to main and manual triggers (workflow_dispatch)
name: Build and deploy Python app to Azure Web App - HelpCare

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: Download SSL Certificate
        run: |
          wget https://dl.cacerts.digicert.com/DigiCertGlobalRootCA.crt.pem
          # Move to a location that will be accessible in production
          mkdir -p ssl-cert
          mv DigiCertGlobalRootCA.crt.pem ssl-cert/

      - name: Create startup script
        run: |
          echo "#!/bin/bash" > startup.sh
          echo "export PGSSLROOTCERT=\$HOME/ssl-cert/DigiCertGlobalRootCA.crt.pem" >> startup.sh
          echo "cd \$HOME" >> startup.sh
          echo "gunicorn --bind=0.0.0.0:8000 --timeout 600 --chdir src helpcare.wsgi:application" >> startup.sh
          chmod +x startup.sh

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'HelpCare'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}