# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

# Note: This file handles Continuous Deployment (CD), and is separate from the django.yml CI file.


# Azure deployment runs on push to main and manual triggers (workflow_dispatch)
# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

# Note: This file handles Continuous Deployment (CD), and is separate from the django.yml CI file.


# Azure deployment runs on push to main and manual triggers (workflow_dispatch)
name: Azure Web App Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: https://helpcare-egcpaqffcefdaag0.canadacentral-01.azurewebsites.net

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Create deployment package
        run: |
          # Create wwwroot structure
          mkdir -p wwwroot
          cp -r src/* wwwroot/
          cp requirements.txt wwwroot/
          
          # Create virtual environment setup script
          cat > wwwroot/setup.sh << 'EOL'
          #!/bin/bash
          python -m venv antenv
          source antenv/bin/activate
          pip install -r requirements.txt
          EOL
          
          # Make setup script executable
          chmod +x wwwroot/setup.sh
          
          # Create startup command file
          cat > wwwroot/startup.txt << 'EOL'
          if [ ! -d "antenv" ]; then
            ./setup.sh
          fi
          source antenv/bin/activate
          cd src && gunicorn helpcare.wsgi:application --bind=0.0.0.0:8000
          EOL
          
          # Generate web.config
          cat > wwwroot/web.config << 'EOL'
          <?xml version="1.0" encoding="utf-8"?>
          <configuration>
            <system.webServer>
              <handlers>
                <add name="PythonHandler" path="*" verb="*" modules="httpPlatformHandler" resourceType="Unspecified"/>
              </handlers>
              <httpPlatform processPath="bash"
                           arguments="%home%\site\wwwroot\startup.txt"
                           stdoutLogEnabled="true"
                           stdoutLogFile="%home%\LogFiles\python.log"
                           startupTimeLimit="180">
                <environmentVariables>
                  <environmentVariable name="PYTHONPATH" value="%home%\site\wwwroot"/>
                  <environmentVariable name="PATH" value="%home%\Python312;%home%\Python312\Scripts;%PATH%"/>
                  <environmentVariable name="DJANGO_SETTINGS_MODULE" value="helpcare.settings"/>
                </environmentVariables>
              </httpPlatform>
            </system.webServer>
          </configuration>
          EOL

      - name: Zip artifact for deployment
        run: |
          cd wwwroot
          zip -r ../wwwroot.zip ./*

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'HelpCare'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: wwwroot.zip
          clean: true